name = "phd-defense-prep"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "phd-defense-db"
database_id = "b67d504e-8e1f-4ac4-9293-d0f42aa9727e"
